"""Durable journal backing the server package's in-memory work queues."""

from __future__ import annotations

import json
import sqlite3
import threading
from pathlib import Path
from typing import Any


class JobJournal:
    """Persist queue snapshots without using SQLite as the scheduling queue."""

    def __init__(self, path: Path) -> None:
        self.path = path.expanduser().resolve()
        self._lock = threading.RLock()
        self._initialized = False

    def connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.path, timeout=30)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA busy_timeout = 30000")
        return connection

    def initialize(self) -> None:
        with self._lock:
            if self._initialized:
                return
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.connect() as connection:
                connection.execute("PRAGMA journal_mode = WAL")
                connection.execute(
                    """
                    CREATE TABLE IF NOT EXISTS job_journal (
                        kind TEXT NOT NULL,
                        version_id TEXT NOT NULL,
                        work_id TEXT NOT NULL,
                        agent_job_id TEXT,
                        job_json TEXT NOT NULL,
                        created_at TEXT NOT NULL,
                        updated_at TEXT NOT NULL,
                        PRIMARY KEY(kind, version_id)
                    )
                    """
                )
                # job_id is generated by Director and is the idempotency key across
                # retries. It is intentionally independent of the logical work_id.
                connection.execute("DROP INDEX IF EXISTS idx_job_journal_idempotency")
                connection.execute(
                    """
                    CREATE UNIQUE INDEX IF NOT EXISTS idx_job_journal_idempotency
                    ON job_journal(kind, agent_job_id)
                    WHERE agent_job_id IS NOT NULL AND agent_job_id != ''
                    """
                )
                connection.execute(
                    "CREATE INDEX IF NOT EXISTS idx_job_journal_updated "
                    "ON job_journal(kind, updated_at)"
                )
            self._initialized = True

    def load(self, kind: str) -> list[dict[str, Any]]:
        with self._lock, self.connect() as connection:
            rows = connection.execute(
                "SELECT job_json FROM job_journal WHERE kind = ? "
                "ORDER BY created_at, version_id",
                (kind,),
            ).fetchall()
        return [json.loads(str(row["job_json"])) for row in rows]

    def get(self, kind: str, version_id: str) -> dict[str, Any] | None:
        with self._lock, self.connect() as connection:
            row = connection.execute(
                "SELECT job_json FROM job_journal WHERE kind = ? AND version_id = ?",
                (kind, version_id),
            ).fetchone()
        return json.loads(str(row["job_json"])) if row else None

    def get_by_agent_job_id(self, kind: str, agent_job_id: str) -> dict[str, Any] | None:
        with self._lock, self.connect() as connection:
            row = connection.execute(
                "SELECT job_json FROM job_journal WHERE kind = ? AND agent_job_id = ?",
                (kind, agent_job_id),
            ).fetchone()
        return json.loads(str(row["job_json"])) if row else None

    def save(self, kind: str, job: dict[str, Any]) -> None:
        payload = json.dumps(job, ensure_ascii=False, separators=(",", ":"))
        with self._lock, self.connect() as connection:
            connection.execute(
                """
                INSERT INTO job_journal (
                    kind, version_id, work_id, agent_job_id, job_json,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(kind, version_id) DO UPDATE SET
                    work_id = excluded.work_id,
                    agent_job_id = excluded.agent_job_id,
                    job_json = excluded.job_json,
                    updated_at = excluded.updated_at
                """,
                (
                    kind,
                    job["version_id"],
                    job["work_id"],
                    job.get("agent_job_id"),
                    payload,
                    job["created_at"],
                    job["updated_at"],
                ),
            )

    def delete(self, kind: str, version_id: str) -> None:
        with self._lock, self.connect() as connection:
            connection.execute(
                "DELETE FROM job_journal WHERE kind = ? AND version_id = ?",
                (kind, version_id),
            )
