export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export interface UIVideo {
  url: string;
  name?: string;
}

export interface UIQuestionCard {
  id: string;
  question: string;
  options: { label: string }[];
  allowCustom?: boolean;
  answered?: string | null;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Assistant turn: resolved video shot URLs rendered inline under the text. */
  videos?: UIVideo[];
  /** Structured question cards embedded in an assistant message. */
  questions?: UIQuestionCard[];
  /** Human approval gate for VLM-selected image/audio memories. */
  memoryReview?: MemoryReview;
  /** Batch id for persisting question-card answers over WebSocket. */
  questionBatchId?: string;
  /** Top-of-turn wait indicator (TypingDots); cleared on ``stream_end resuming:false``. */
  turnWaiting?: boolean;
}

/** Wire shape for question cards on inbound WS / session replay. */
export interface WireQuestionCard {
  id: string;
  question: string;
  options: Array<string | { label: string }>;
  allow_custom?: boolean;
  allowCustom?: boolean;
  answered?: string | null;
  status?: string;
}

export interface WireMediaRef {
  url: string;
  name?: string;
}

export type MemoryReviewStatus =
  | "awaiting_method"
  | "selecting"
  | "awaiting_review"
  | "reselecting"
  | "approved"
  | "error";

export interface MemorySelection {
  memory_id: string;
  /** Human-readable label for UI; falls back to memory_id when absent. */
  display_name?: string;
  kind: "character" | "previous_shot";
  candidate_index: number;
  frame_index: number;
  timestamp_sec: number;
  confidence: number;
  visual_status: string;
  reasoning: string;
  source_shot_id: number;
  audio_source_shot_id?: number | null;
  image: WireMediaRef;
  audio?: WireMediaRef | null;
}

/** Prefer display_name for UI labels; keep memory_id as stable fallback. */
export function memoryDisplayName(
  memory: { display_name?: string | null; memory_id?: string; id?: string },
): string {
  const label = memory.display_name?.trim();
  if (label) return label;
  return (memory.memory_id || memory.id || "").trim();
}

export interface MemoryReviewAttempt {
  attempt: number;
  rejected_candidate_indices: number[];
  selections: MemorySelection[];
  updated_at: string;
}

export interface MemoryReview {
  review_id: string;
  shot_id: number;
  status: MemoryReviewStatus;
  attempt: number;
  candidate_count: number;
  rejected_candidate_indices: number[];
  selections: MemorySelection[];
  selection_mode?: "manual" | "vlm" | null;
  required_memory_ids?: string[];
  manual_selected_ids?: string[];
  /** References the user chose to keep; an empty list is valid. */
  retained_memory_ids?: string[];
  /** Generated shot video used for VLM and manual frame selection. */
  source_video?: WireMediaRef | null;
  history: MemoryReviewAttempt[];
  error?: string | null;
  updated_at: string;
}

export interface GenerationMemory {
  id: string;
  /** Stable Memory Workspace asset id used to restore a shot's slot draft. */
  workspace_asset_id?: string;
  /** Human-readable label for UI; falls back to id when absent. */
  display_name?: string;
  image: WireMediaRef;
  audio?: WireMediaRef | null;
  metadata: {
    source?: string;
    visual_status?: string;
    source_shot_id?: number | null;
    frame_index?: number | null;
    timestamp_sec?: number | null;
    confidence?: number | null;
    audio_source_shot_id?: number | null;
    audio_workspace_asset_id?: string;
    reference_type?: MemoryReferenceType;
    reference_label?: string;
    identity_ids?: string[];
    profile_text?: string;
  };
}

export type MemoryWorkspaceSource = "automatic" | "local";
export type MemoryReferenceType =
  | "character"
  | "scene"
  | "style"
  | "object"
  | "other";

/** One reusable item in the per-project local Memory Workspace. */
export interface MemoryWorkspaceAsset {
  asset_id: string;
  display_name: string;
  source: MemoryWorkspaceSource;
  kind: "character" | "previous_shot" | "manual";
  memory_id?: string;
  source_shot_id?: number | null;
  frame_index?: number | null;
  image?: WireMediaRef;
  audio?: WireMediaRef | null;
  media_type?: "image" | "audio" | "image_audio";
  profile_text?: string;
  profile_status?: "ready" | "missing" | "profiling" | "error" | string;
  profile_source?: "vlm" | "human" | "none" | string;
  identity_ids?: string[];
  reference_type?: MemoryReferenceType;
  reference_label?: string;
  provenance?: {
    source: "generated_shot" | "local_upload" | string;
    shot_id?: number | null;
    timestamp_sec?: number | null;
  };
}

/** Compact reference persisted when applying an ordered slot draft to a shot. */
export interface MemorySlotReference {
  source?: MemoryWorkspaceSource;
  asset_id?: string;
  image_asset_id?: string;
  audio_asset_id?: string;
  reason?: string;
}

export interface MemoryAssetUpload {
  asset_id?: string;
  display_name?: string;
  image?: OutboundMedia;
  audio?: OutboundMedia;
  remove_audio?: boolean;
  profile_text?: string;
  identity_ids?: string[];
  reference_type?: MemoryReferenceType | null;
  reference_label?: string;
}

export interface ShotMemoryAssetCreate {
  timestamp_sec: number;
  reference_type: MemoryReferenceType;
  reference_label?: string;
  profile_text?: string;
  include_audio?: boolean;
  audio_start_sec?: number;
  audio_end_sec?: number;
}

export interface StoryProfileBeat {
  shot_id: number;
  summary: string;
}

export interface StoryProfile {
  summary?: string;
  beats?: StoryProfileBeat[];
  characters?: unknown;
  genre?: string;
  setting?: string;
  title?: string;
  tone?: string;
  language?: string;
  dialogue_language?: string;
  anchors?: unknown;
  shot_to_content?: Record<string, string>;
  content_to_shots?: Record<string, string[]>;
  [key: string]: unknown;
}

export interface WorkplaceShot {
  shot_id: number;
  shot_key: string;
  status: string;
  summary: string;
  caption?: string;
  num_frames?: number | null;
  cut: boolean;
  video?: WireMediaRef | null;
  has_video: boolean;
  has_actions: boolean;
  accepted: boolean;
  last_review?: string | null;
  review_notes?: string;
  generation_error?: string;
  /** R2V remote version id when generation has been submitted. */
  version_id?: string;
  /** Raw Echo/R2V job status mirrored from shot.echo.status. */
  echo_status?: string;
  updated_at?: string | null;
  planned_reference_shot_ids?: number[];
  reference_shot_ids?: number[];
  reference_selection_note?: string;
  references_planned?: boolean;
  memory_review?: Omit<MemoryReview, "shot_id"> | null;
  /** Exact Memory slots submitted when this shot generation was queued. */
  generation_memories?: GenerationMemory[];
  /** Ordered Memory Workspace slots currently applied to this shot. */
  memory_slots?: GenerationMemory[];
  memory_slots_configured?: boolean;
  /** Stable references already approved in Build Memory. */
  approved_memory_slot_refs?: MemorySlotReference[];
  /** Agent/profile recommendation; never sent to R2V until explicitly applied. */
  recommended_memory_slots?: GenerationMemory[];
  recommended_memory_slot_refs?: MemorySlotReference[];
  memory_recommendation_source?: "agent" | "profile_fallback" | string | null;
  /** 是否开启首尾衔接（使用前一 Shot 尾帧作为 I2V 条件图） */
  continuous_enabled?: boolean;
  /** 本镜头视频尾帧的持久化 URL（由下一次 continuous-generate 提取并回写） */
  tail_frame_url?: string;
  timeline: {
    start_seconds: number;
    end_seconds: number;
    duration_seconds: number;
    label: string;
  };
}

/** User-uploaded first-frame reference image for shot 1. */
export interface WorkplaceReferenceImage {
  url: string;
  name?: string;
  width?: number;
  height?: number;
}

export interface WorkplaceData {
  session_key: string;
  work_id: string | null;
  story_md: string;
  story_empty: boolean;
  story_profile?: StoryProfile;
  story_editable?: boolean;
  beats_editable?: boolean;
  story_confirmed?: boolean;
  shot_prompts_ready?: boolean;
  shot_prompts_progress?: { ready: number; total: number } | null;
  references_ready?: boolean;
  /** ISO timestamp when stage entered shot_generating via start-generation. */
  shot_generating_started_at?: string | null;
  stage: string | null;
  goal: Record<string, unknown>;
  final_output_path?: string | null;
  final_output_url?: string | null;
  final_video?: WireMediaRef | null;
  /** Durable character identities plus the latest previous-shot continuity slot. */
  memory_bank?: MemorySelection[];
  /** Automatic and locally uploaded assets available for slot assembly. */
  memory_workspace_assets?: MemoryWorkspaceAsset[];
  /** Human-readable generation failure when the workflow stage is ``failed``. */
  generation_error?: string | null;
  /**
   * Shot1 first-frame reference image persisted by the backend.
   * Composer PUT/DELETE; shot 1 I2V reads this from state.
   */
  reference_image?: WorkplaceReferenceImage | null;
  /** True after shot count is confirmed; PUT/DELETE then 409. */
  reference_image_locked?: boolean;
  /** Generate remaining shots automatically after story confirmation. */
  auto_generate?: boolean;
  /** Workflow bar: ``01``–``04`` or ``done``. */
  progress?: "01" | "02" | "03" | "04" | "done" | string | null;
  /** Echo tracking: remote request id; LikeButton hidden when absent. */
  echo_request_id?: string | null;
  /** Echo tracking: 0 = none, 1 = like, 2 = dislike. */
  like_status?: number;
  prompt_downloaded?: boolean;
  video_downloaded?: boolean;
  shots: WorkplaceShot[];
  updated_at: string | null;
}

export type EchoTrackingResponse = {
  ok: boolean;
  session_key: string;
  echo_request_id: string | null;
  like_status: number;
  prompt_downloaded: boolean;
  video_downloaded: boolean;
  workplace: WorkplaceData;
};

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  preview: string;
  /** Director workflow source. */
  source?: "stepwise" | null;
  /** Stepwise auto-generate flag persisted on the session. */
  autoGenerate?: boolean | null;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
  /** Local browser identity used to namespace on-disk sessions. */
  user_id?: string | null;
  /** Currently active Prompt Engineering set name (server-global). */
  active_pe?: string | null;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string; active_pe?: string }
  | {
      event: "workplace_updated";
      chat_id: string;
      work_id?: string;
      workplace?: WorkplaceData;
    }
  | {
      event: "workplace_action_ok";
      chat_id: string;
      request_id: string;
      work_id: string;
      workplace: WorkplaceData;
    }
  | {
      event: "workplace_action_error";
      chat_id: string;
      request_id: string;
      detail: string;
    }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: WireMediaRef[];
      questions?: WireQuestionCard[];
      question_batch_id?: string;
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress";
    }
  | {
      event: "question_answer_ok";
      chat_id: string;
      question_batch_id: string;
      card_id: string;
      value: string;
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
      /** ``false`` means the agent turn is finished; question cards may be answered. */
      resuming?: boolean;
    }
  | { event: "pe_updated"; chat_id: string; active: string }
  | { event: "error"; chat_id?: string; detail?: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export type Outbound =
  | { type: "new_chat"; autoGenerate?: boolean }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      temperature?: number;
      top_p?: number;
      top_k?: number;
      autoGenerate?: boolean;
      duration_sec?: number;
      reference_image_url?: string;
      reference_image_name?: string;
      reference_image_width?: number;
      reference_image_height?: number;
    }
  | {
      type: "workplace_save_story";
      chat_id: string;
      request_id: string;
      story_md: string;
    }
  | {
      type: "workplace_save_story_profile";
      chat_id: string;
      request_id: string;
      story_profile: StoryProfile;
    }
  | {
      type: "workplace_save_reference_image";
      chat_id: string;
      request_id: string;
      image: WorkplaceReferenceImage;
    }
  | {
      type: "workplace_save_memory_asset";
      chat_id: string;
      request_id: string;
      asset: MemoryAssetUpload;
    }
  | {
      type: "workplace_create_shot_memory_asset";
      chat_id: string;
      request_id: string;
      shot_id: number;
      asset: ShotMemoryAssetCreate;
    }
  | {
      type: "workplace_delete_memory_asset";
      chat_id: string;
      request_id: string;
      asset_id: string;
    }
  | {
      type: "workplace_save_shot_memory_slots";
      chat_id: string;
      request_id: string;
      shot_id: number;
      slots: MemorySlotReference[];
    }
  | {
      type: "answer_question";
      chat_id: string;
      question_batch_id: string;
      card_id: string;
      value: string;
    }
  | { type: "set_pe"; name: string; chat_id: string };
